{
"sureDelEnts": "¿Estás seguro de que quieres eliminar todos los datos de entidades? ¡Esta acción no se puede deshacer!",
"order_cancel": "Tu pedido ha sido cancelado",
"shiplocker": "Casillero de Paquetes",
"config_ships_desc": "Configurar lista negra o blanca de artículos para pedir",
"noshipstopick": "No tienes ningún envío para recoger aquí",
"save": "Guardar",
"shipdelivered_locker": "Entregaste un paquete a un casillero de paquetes.",
"couriertrucks_config": "Configuración",
"order_itemadded": "El artículo ha sido agregado a la lista de pedidos",
"truck_is_toofar1": "Tu vehículo está demasiado lejos",
"couriertrucks_vendoravail": "El vehículo está disponible en el vendedor de camiones",
"locate": "Localizar",
"recipient_leftfromserver": "Algunos paquetes han sido eliminados debido a que el destinatario se desconectó del servidor",
"trunktext2": "Abrir",
"got_new_truck": "Recibiste el camión de mensajería.",
"couriertrucks_skin": "Skin",
"courier_notify": "Recibes una notificación cuando se asigna un envío a un mensajero",
"packeditor_enttype": "Elige un tipo y una entidad",
"couriertrucks_customize": "Personalizar",
"parcel_shipname": "Sr. Envío",
"orderfinalized": "El carrito ha sido confirmado. Selecciona un método de entrega",
"orders": "Pedidos",
"config_langs_desc": "Cambia el idioma o crea uno nuevo",
"deliverypnl_courierdesc": "El pedido se entregará directamente en tus manos",
"shipdelayed": "No entregaste el envío por %s en el tiempo especificado, así que no recibirás dinero por la entrega",
"shiplockers": "Casilleros de Paquetes",
"prefix": "es",
"parcel_waypointadd": "El casillero de paquetes ha sido agregado a tus puntos de referencia.",
"sortingmachine": "Máquina Clasificadora",
"deliverypnl_parcelname": "Casillero de Paquetes",
"truck_is_toofar2": "No puedes tomar un nuevo vehículo porque el anterior está demasiado lejos.",
"packeditor_choosetbl": "Elige una tabla",
"truck_notexists": "El camión no existe.",
"order_itemremoved": "El artículo ha sido eliminado de la lista de pedidos",
"delayed": "Retrasado",
"cancel": "Cancelar",
"config_trucks_title": "Configuración de Camiones",
"plynohavetruck": "No tienes vehículo de mensajería o el vehículo ha sido eliminado.",
"shipappeared": "Apareció un nuevo envío en el almacén",
"deliverypnl_title": "Opciones de Envío",
"weapon": "Arma",
"deliverypnl_pickname": "Recoger tú mismo",
"fullcart": "Tu carrito está lleno.",
"couriertrucks_noselectedcar": "Elige el camión que deseas recibir",
"shipdelivered_courier": "El paquete fue entregado y desempaquetado por el destinatario.",
"config_ships_title": "Lista Blanca/Negra",
"availablepacks": "Paquetes Disponibles",
"yourtookshipforlocker": "Recogiste un envío para ser entregado a uno de los casilleros de paquetes",
"parcel_receivparcels": "Recibir tus paquetes",
"notacourier": "No puedes hacer esto porque no eres un mensajero.",
"langedit": "Editor de Idiomas",
"nowarehouseent": "La entidad de almacén no ha sido generada.",
"couriertrucks_returncar": "Devolver el vehículo actual",
"sureDeliShip": "¿Estás seguro de que quieres entregar este envío?",
"config_trucks_desc": "Configurar o eliminar camiones de mensajería agregados con la pistola de herramientas",
"courier_waypointadd": "Puedes localizar al mensajero %s usando el punto de referencia.",
"packeditor_title": "Agregar una nueva entidad",
"orderlist": "Lista de Pedidos",
"couriertrucks_plysetskin": "Los jugadores pueden establecer la skin del vehículo",
"truck_notconfigured": "El camión no ha sido configurado.",
"yourship": "No puedes escanear el envío para que te lo entreguen",
"trunktext1": "Maletero del Camión",
"shipdelivered": "Recogiste tu paquete.",
"yourship_locate": "No puedes localizar el envío para que te lo entreguen",
"config_settings_desc": "La configuración principal del script",
"truck_notruckplatform": "La entidad de estacionamiento de camiones no ha sido generada.",
"parcel_isready": "¡Tu paquete está listo!",
"earnedmoney": "Ganaste %s",
"parcel_parcels": "Paquetes Dentro",
"availableitems": "Artículos Disponibles",
"shipdelayed_locker": "No entregaste el envío para uno de los casilleros de paquetes en el tiempo especificado, así que no recibirás el bono de dinero extra por la entrega",
"couriertrucks_color": "Color",
"sureExitLang": "¿Estás seguro de que quieres salir? ¡Tienes cambios sin guardar!",
"packinfo": "Información del Envío",
"parcel_busybox": "No puedes recoger tu paquete ahora. Inténtalo de nuevo más tarde.",
"config_settings_title": "Configuración Principal",
"deliverypnl_dronename": "Dron de Entrega",
"cantDo": "No puedes hacer eso.",
"couriertrucks_cannotcustomize": "Este vehículo no se puede personalizar",
"shipdelivered_lockerreminder": "Tu paquete ha sido colocado en un casillero de paquetes",
"parcel_waypointremove": "Eliminaste el casillero de paquetes de tus puntos de referencia.",
"confirm": "Confirmar",
"trunktext3": "Robar el Maletero",
"shiptaken": "Este envío será entregado por otro mensajero",
"courier_leftfromserver_text1": "Los paquetes fueron colocados en el casillero de paquetes más cercano debido a la ausencia del mensajero que debía entregarlos",
"deliverypnl_couriername": "Entrega Directa",
"parcel_putparcels": "Poner en el paquete",
"couriertrucks_plysetcolor": "Los jugadores pueden establecer el color del vehículo",
"yourtookshipforply": "Tomaste un envío para: %s. ¡Recuerda verificar la ubicación del destinatario en el maletero del camión o con un escáner!",
"couriertookship": "Tu envío será tomado por %s",
"config_ships_checkbox": "Habilitar una lista negra en lugar de una lista blanca",
"alreadyscan": "Este envío ya ha sido escaneado",
"deliverypnl_desc": "Has realizado un nuevo pedido. Elige tu opción de envío",
"couriertrucks_takeacar": "Tomar un nuevo vehículo",
"cartcontains": "El carrito contiene",
"config_langs_title": "Idiomas",
"no_locker_available": "No hay casilleros de paquetes disponibles. Debes recoger el envío personalmente",
"deliverypnl_parceldesc": "El pedido se entregará en el casillero de paquetes",
"nofreespace": "No se encontró espacio libre para generar la entidad.",
"recipient_waypointadd": "%s ha sido agregado a tus puntos de referencia.",
"truck_returned": "El vehículo fue devuelto con éxito.",
"couriertrucks_bgs": "Grupos de Cuerpo",
"couriertrucks_overappeara": "Apariencia Anulada",
"locker_notify": "Recibes una notificación cuando el envío está en la máquina de paquetes",
"couriertrucks_title": "Camiones de Mensajería",
"added_to_exists": "El pedido fue agregado al envío anteriormente ordenado",
"takeit": "Sácalo",
"empty_trunk": "El maletero está vacío.",
"ammo": "Munición",
"entity": "Entidad",
"couriertrucks_plysetbgs": "Los jugadores pueden establecer los grupos de cuerpo del vehículo",
"confirmWin": "Ventana de Confirmación",
"warehouse": "Almacén",
"recipient_waypointremove": "Eliminaste %s de tus puntos de referencia.",
"courier_leftfromserver_text2": "Los paquetes regresaron al almacén debido a la ausencia del mensajero. Puedes recogerlos en persona o esperar a otro mensajero",
"items": "artículo(s)",
"parcel_canhelp": "¡Hola! ¿Cómo puedo ayudarte?",
"orderconfirmed": "El pedido ha sido confirmado y está en proceso",
"deliverypnl_pickdesc": "Debes recoger el envío tú mismo en el almacén",
"deliverypnl_dronedesc": "El pedido será entregado por dron",
"full_name": "Español"
}
